"use client";

import { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import {
    FileText,
    Shield,
    Sparkles,
    ArrowLeft,
    Search,
    Printer,
    CheckCircle2,
    Scale,
    Zap,
    AlertCircle,
    UserCheck,
    CreditCard,
    Lock,
    HelpCircle,
    ChevronRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useSettings } from "@/contexts/SettingsContext";

const sections = [
    {
        id: "acceptance",
        title: "1. Acceptance of Terms",
        icon: UserCheck,
        content: `By accessing or using AI Suite ("the Platform", "we", "us", or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you are expressly prohibited from using the Platform and must discontinue use immediately.

These Terms apply to all visitors, registered users, subscribers, and others who access or use our AI tools, APIs, autonomous agents, and related services.`,
        highlights: ["Must be at least 18 years of age or have legal parental consent.", "By creating an account, you confirm all provided information is accurate."],
    },
    {
        id: "account",
        title: "2. Account Credentials & Security",
        icon: Lock,
        content: `To access certain features of the Platform, you may be required to register for an account. You agree to safeguard your credentials and remain responsible for any activity under your account.

You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate our security policies or show suspicious automated activity.`,
        highlights: ["Do not share API keys or login credentials with unauthorized third parties.", "Multi-Factor Authentication (2FA) is strongly recommended for enterprise tiers."],
    },
    {
        id: "ai-services",
        title: "3. AI Tools & Generation Usage",
        icon: Zap,
        content: `AI Suite provides access to 130+ specialized AI tools, language models, image generators, code creators, and autonomous agents.

You acknowledge that output generated by artificial intelligence models ("AI Content") is probabilistic and may occasionally contain inaccuracies, hallucinations, or incomplete data. You are solely responsible for evaluating and verifying AI-generated outputs prior to commercial or critical deployment.`,
        highlights: [
            "Outputs are generated dynamically based on user prompts and model parameters.",
            "You retain ownership of rights to input prompts and valid output creations to the extent permitted by law.",
            "Do not use AI tools to generate harmful, illicit, deceptive, or infringing content.",
        ],
    },
    {
        id: "tokens-subscriptions",
        title: "4. Tokens, Credits & Subscriptions",
        icon: CreditCard,
        content: `Access to tools is governed by a token and credit consumption system. Token costs per tool operation are explicitly stated within the application dashboard.

Subscribers receive a monthly allocation of tokens. Unused tokens roll over or expire depending on your plan tier. Purchases of add-on token packs and subscription fees are non-refundable except where required by applicable consumer protection laws.`,
        highlights: [
            "New accounts receive 1,000 complimentary starter tokens upon email verification.",
            "Subscriptions renew automatically unless canceled prior to the billing cycle.",
        ],
    },
    {
        id: "acceptable-use",
        title: "5. Acceptable Use Policy",
        icon: Shield,
        content: `You agree not to use the Platform to:
• Reverse engineer, decompile, or attempt to extract source code or AI weights.
• Bypass token consumption rate limits or exploit security vulnerabilities.
• Generate spam, malware, phishing content, hate speech, or explicit illegal material.
• Scrape data or train competing artificial intelligence models without explicit written permission.

Violations of this policy will result in immediate permanent account termination without refund.`,
        highlights: ["Zero tolerance for automated abuse, DDoS attempts, or key scraping."],
    },
    {
        id: "intellectual-property",
        title: "6. Intellectual Property Rights",
        icon: Scale,
        content: `The Platform structure, logos, UI designs, tool architecture, algorithms, and brand assets are the exclusive intellectual property of AI Suite and its licensors.

Subject to your compliance with these Terms, AI Suite grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Platform for your internal business or personal creative purposes.`,
        highlights: ["All platform software and proprietary agent architectures remain our property."],
    },
    {
        id: "liability",
        title: "7. Limitation of Liability",
        icon: AlertCircle,
        content: `To the maximum extent permitted by applicable law, AI Suite shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, goodwill, or service interruptions.

Our total cumulative liability arising out of or related to your use of the Platform is limited to the greater of $100 or the total amount paid by you to AI Suite in the twelve (12) months preceding the claim.`,
        highlights: ["Services are provided on an 'AS IS' and 'AS AVAILABLE' basis."],
    },
    {
        id: "termination",
        title: "8. Termination & Amendments",
        icon: CheckCircle2,
        content: `We reserve the right to modify these Terms at any time. We will provide notice of material updates via email or platform announcements. Continued use of the Platform after updates constitutes acceptance.

You may cancel your account at any time via the Settings page. We reserve the right to suspend accounts for non-payment or policy violations.`,
        highlights: ["Notice of changes will be published with an updated effective date."],
    },
];

export default function TermsPage() {
    const { settings } = useSettings();
    const [searchQuery, setSearchQuery] = useState("");
    const [activeSection, setActiveSection] = useState("acceptance");

    const siteName = settings?.metadata?.siteName || "AI Suite";

    const filteredSections = sections.filter(
        (sec) =>
            sec.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
            sec.content.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="min-h-screen bg-background text-foreground py-10 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
            {/* Top Navigation / Breadcrumb */}
            <div className="flex items-center justify-between mb-8">
                <Link
                    href="/"
                    className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-primary transition"
                >
                    <ArrowLeft className="w-4 h-4" />
                    Back to Home
                </Link>
                <div className="flex items-center gap-3">
                    <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
                        <Printer className="w-4 h-4" />
                        Print Page
                    </Button>
                    <Link href="/privacy">
                        <Button variant="secondary" size="sm" className="gap-2">
                            <Shield className="w-4 h-4" />
                            Privacy Policy
                        </Button>
                    </Link>
                </div>
            </div>

            {/* Header Hero */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center max-w-3xl mx-auto mb-12"
            >
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wider mb-4">
                    <Scale className="w-4 h-4" />
                    Legal Documentation
                </div>
                <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-4 gradient-text-primary">
                    Terms of Service
                </h1>
                <p className="text-lg text-muted-foreground leading-relaxed">
                    Please read these terms carefully before using {siteName}. They govern your access to our AI tools, APIs, and workspace services.
                </p>
                <div className="mt-4 inline-flex items-center gap-2 text-xs text-muted-foreground bg-muted/60 px-3 py-1.5 rounded-full border border-border">
                    <Sparkles className="w-3.5 h-3.5 text-primary" />
                    Last Updated: August 30, 2026 • Version 5.2
                </div>
            </motion.div>

            {/* Search Bar */}
            <div className="max-w-xl mx-auto mb-10 relative">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                    type="text"
                    placeholder="Search terms, policies, or clauses..."
                    className="pl-11 pr-4 py-6 rounded-2xl bg-card border-border shadow-sm text-sm"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                />
            </div>

            {/* Main Content Layout */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Left Sidebar Table of Contents */}
                <div className="lg:col-span-4">
                    <div className="sticky top-24 space-y-2 p-4 rounded-2xl border border-border bg-card/60 backdrop-blur-xl shadow-lg">
                        <h3 className="text-sm font-semibold text-muted-foreground px-3 mb-3 uppercase tracking-wider">
                            Table of Contents
                        </h3>
                        {sections.map((sec) => {
                            const Icon = sec.icon;
                            const isActive = activeSection === sec.id;
                            return (
                                <a
                                    key={sec.id}
                                    href={`#${sec.id}`}
                                    onClick={() => setActiveSection(sec.id)}
                                    className={`flex items-center justify-between px-3.5 py-2.5 rounded-xl text-sm font-medium transition ${
                                        isActive
                                            ? "bg-primary text-primary-foreground shadow-md"
                                            : "hover:bg-muted text-muted-foreground hover:text-foreground"
                                    }`}
                                >
                                    <div className="flex items-center gap-3 truncate">
                                        <Icon className="w-4 h-4 shrink-0" />
                                        <span className="truncate">{sec.title}</span>
                                    </div>
                                    <ChevronRight className="w-3.5 h-3.5 shrink-0 opacity-60" />
                                </a>
                            );
                        })}
                    </div>
                </div>

                {/* Right Content Sections */}
                <div className="lg:col-span-8 space-y-8">
                    {filteredSections.length === 0 ? (
                        <div className="text-center py-12 p-8 rounded-2xl border border-border bg-card">
                            <HelpCircle className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
                            <h3 className="text-lg font-semibold mb-1">No matching sections found</h3>
                            <p className="text-sm text-muted-foreground">
                                Try searching for terms like "tokens", "account", or "liability".
                            </p>
                        </div>
                    ) : (
                        filteredSections.map((sec) => {
                            const Icon = sec.icon;
                            return (
                                <motion.section
                                    key={sec.id}
                                    id={sec.id}
                                    initial={{ opacity: 0, y: 15 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true, margin: "-50px" }}
                                    className="p-6 sm:p-8 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition"
                                >
                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="p-2.5 rounded-xl bg-primary/10 text-primary">
                                            <Icon className="w-5 h-5" />
                                        </div>
                                        <h2 className="text-xl sm:text-2xl font-bold">{sec.title}</h2>
                                    </div>

                                    <div className="text-muted-foreground leading-relaxed whitespace-pre-line text-sm sm:text-base space-y-4">
                                        {sec.content}
                                    </div>

                                    {sec.highlights && sec.highlights.length > 0 && (
                                        <div className="mt-6 pt-4 border-t border-border space-y-2">
                                            <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                                                Key Highlights
                                            </h4>
                                            {sec.highlights.map((item, idx) => (
                                                <div key={idx} className="flex items-start gap-2 text-xs sm:text-sm text-foreground">
                                                    <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                                    <span>{item}</span>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </motion.section>
                            );
                        })
                    )}

                    {/* Bottom Legal Support Card */}
                    <div className="p-6 rounded-2xl bg-gradient-to-r from-primary/10 via-ai-secondary/10 to-ai-tertiary/10 border border-primary/20 flex flex-col sm:flex-row items-center justify-between gap-4">
                        <div>
                            <h3 className="font-bold text-lg mb-1">Have legal or policy questions?</h3>
                            <p className="text-sm text-muted-foreground">
                                Our legal and compliance team is available to help answer your inquiries.
                            </p>
                        </div>
                        <a href="mailto:support@aisuite.com">
                            <Button className="shrink-0 gap-2">
                                Contact Legal Team
                            </Button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
}
